// Core editor toolbar items are host-owned (non-plugin) but keep the same
// contribution shape as plugin editorToolbar items so external plugins can
// extend the toolbar through the existing registry.

function cmd(command, ...args) {
  return (editor) => {
    if (!editor) return;
    editor.chain().focus()[command](...args).run();
  };
}

export const CORE_EDITOR_TOOLBAR_ITEMS = [
  {
    id: 'bold',
    label: 'editorToolbar.bold',
    icon: 'Bold',
    type: 'button',
    group: 'format',
    priority: 100,
    action: cmd('toggleBold'),
    isActive: (editor) => editor.isActive('bold'),
    isDisabled: (editor) => (editor ? !editor.can().chain().focus().toggleBold().run() : true),
  },
  {
    id: 'italic',
    label: 'editorToolbar.italic',
    icon: 'Italic',
    type: 'button',
    group: 'format',
    priority: 90,
    action: cmd('toggleItalic'),
    isActive: (editor) => editor.isActive('italic'),
    isDisabled: (editor) => (editor ? !editor.can().chain().focus().toggleItalic().run() : true),
  },
  {
    id: 'strike',
    label: 'editorToolbar.strike',
    icon: 'Strikethrough',
    type: 'button',
    group: 'format',
    priority: 80,
    action: cmd('toggleStrike'),
    isActive: (editor) => editor.isActive('strike'),
  },
  {
    id: 'textAlign',
    label: 'editorToolbar.align',
    type: 'dropdown',
    group: 'align',
    priority: 78,
    action: cmd('setTextAlign', 'left'),
    isDisabled: () => false,
    children: [
      {
        id: 'alignLeft',
        label: 'editorToolbar.alignLeft',
        icon: 'AlignLeft',
        action: cmd('setTextAlign', 'left'),
        isActive: (editor) => editor.isActive({ textAlign: 'left' }),
      },
      {
        id: 'alignCenter',
        label: 'editorToolbar.alignCenter',
        icon: 'AlignCenter',
        action: cmd('setTextAlign', 'center'),
        isActive: (editor) => editor.isActive({ textAlign: 'center' }),
      },
      {
        id: 'alignRight',
        label: 'editorToolbar.alignRight',
        icon: 'AlignRight',
        action: cmd('setTextAlign', 'right'),
        isActive: (editor) => editor.isActive({ textAlign: 'right' }),
      },
      {
        id: 'alignJustify',
        label: 'editorToolbar.alignJustify',
        icon: 'AlignJustify',
        action: cmd('setTextAlign', 'justify'),
        isActive: (editor) => editor.isActive({ textAlign: 'justify' }),
      },
    ],
  },
  {
    id: 'heading',
    label: 'editorToolbar.heading',
    type: 'dropdown',
    group: 'heading',
    priority: 76,
    action: cmd('setParagraph'),
    isDisabled: () => false,
    children: [
      {
        id: 'paragraph',
        label: 'editorToolbar.paragraph',
        icon: 'Pilcrow',
        action: cmd('setParagraph'),
        isActive: (editor) => editor.isActive('paragraph'),
      },
      {
        id: 'heading1',
        label: 'editorToolbar.heading1',
        icon: 'Heading1',
        action: cmd('toggleHeading', { level: 1 }),
        isActive: (editor) => editor.isActive('heading', { level: 1 }),
      },
      {
        id: 'heading2',
        label: 'editorToolbar.heading2',
        icon: 'Heading2',
        action: cmd('toggleHeading', { level: 2 }),
        isActive: (editor) => editor.isActive('heading', { level: 2 }),
      },
      {
        id: 'heading3',
        label: 'editorToolbar.heading3',
        icon: 'Heading3',
        action: cmd('toggleHeading', { level: 3 }),
        isActive: (editor) => editor.isActive('heading', { level: 3 }),
      },
      {
        id: 'heading4',
        label: 'editorToolbar.heading4',
        icon: 'Heading4',
        action: cmd('toggleHeading', { level: 4 }),
        isActive: (editor) => editor.isActive('heading', { level: 4 }),
      },
      {
        id: 'heading5',
        label: 'editorToolbar.heading5',
        icon: 'Heading5',
        action: cmd('toggleHeading', { level: 5 }),
        isActive: (editor) => editor.isActive('heading', { level: 5 }),
      },
      {
        id: 'heading6',
        label: 'editorToolbar.heading6',
        icon: 'Heading6',
        action: cmd('toggleHeading', { level: 6 }),
        isActive: (editor) => editor.isActive('heading', { level: 6 }),
      },
    ],
  },
  {
    id: 'bulletList',
    label: 'editorToolbar.bulletList',
    icon: 'List',
    type: 'button',
    group: 'list',
    priority: 60,
    action: cmd('toggleBulletList'),
    isActive: (editor) => editor.isActive('bulletList'),
  },
  {
    id: 'orderedList',
    label: 'editorToolbar.orderedList',
    icon: 'ListOrdered',
    type: 'button',
    group: 'list',
    priority: 50,
    action: cmd('toggleOrderedList'),
    isActive: (editor) => editor.isActive('orderedList'),
  },
  {
    id: 'horizontalRule',
    label: 'editorToolbar.horizontalRule',
    icon: 'Minus',
    type: 'button',
    group: 'insert',
    priority: 40,
    action: cmd('setHorizontalRule'),
  },
  {
    id: 'clearFormat',
    label: 'editorToolbar.clearFormat',
    icon: 'RemoveFormatting',
    type: 'button',
    group: 'clear',
    priority: 30,
    action: cmd('unsetAllMarks'),
  },
  {
    id: 'undo',
    label: 'editorToolbar.undo',
    icon: 'Undo',
    type: 'button',
    group: 'history',
    priority: 20,
    action: cmd('undo'),
    isDisabled: (editor) => (editor ? !editor.can().chain().focus().undo().run() : true),
  },
  {
    id: 'redo',
    label: 'editorToolbar.redo',
    icon: 'Redo',
    type: 'button',
    group: 'history',
    priority: 10,
    action: cmd('redo'),
    isDisabled: (editor) => (editor ? !editor.can().chain().focus().redo().run() : true),
  },
];
